#!/bin/sh

font=/mnt/font/SourceCodePro-Medium/11a/font
export font

export PATH="$HOME/helperscripts/acme-tools:$PLAN9/bin:$PATH" \
    EDITOR=E \
    SHELL=rc \
    PAGER=nobs \
    TERM=dumb \
    NO_COLOR=1

if ! pgrep -x plumber >/dev/null; then
    plumber
    cat $HOME/lib/plumbing | 9p write plumb/rules # may need the plumber
fi

9term -f $font rc