#!/bin/sh

font=/mnt/font/FiraMono-Medium/12a/font
export font

export PATH="$HOME/helperscripts/p9tools:$PLAN9/bin:$PATH" \
    EDITOR=E \
    SHELL=rc \
    PAGER=nobs \
    TERM=dumb \
    NO_COLOR=1

if ! pgrep -x plumber >/dev/null; then
    plumber
fi

cat $HOME/lib/plumbing | 9p write plumb/rules # may need the plumber

9term -f $font rc