#!/bin/sh

fontdir="$PLAN9/font"
font=/mnt/font/IBMPlexMono-Text/11a/font

export PATH="$HOME/helperscripts/acme-tools:$PATH"
export EDITOR=E
export acmeshell=/bin/sh
export SHELL=/bin/sh
export PAGER=cat

if ! pgrep -x plumber >/dev/null; then
    plumber
fi

acme -a -f $font $* &
