#!/bin/sh
# Launch acme editor detached and
# without writing output to terminal.

TERM=dumb
PAGER=nobs

if [ -f "./acme.dump" ]; then
	load_dump="-l ./acme.dump"
fi

acme -a $load_dump -f /mnt/font/'JetBrainsMono-Regular'/9a/font $* > /dev/null 2>&1 &
