#!/bin/bash

if [ ! -f $1 ]
then
	echo "!ERROR: file $1 not found. No diff performed"
	exit 1
fi

if [ ! -f $2 ]
then
	echo "!ERROR: file $2 not found. No diff performed"
	exit 1
fi

tmpdir=/tmp/diff-pdf
mkdir -p $tmpdir
tmpdiff="$(echo $1 | sed -e 's/\///g')"

echo "Diffing $1 vs $2"
if [ -z "$noview" ]; then
    diff-pdf -ms --output-diff=$tmpdir/$tmpdiff $1 $2 && rm $tmpdir/$tmpdiff || atril $tmpdir/$tmpdiff
else
    diff-pdf -ms --output-diff=$tmpdir/$tmpdiff $1 $2 && rm $tmpdir/$tmpdiff || echo "Diff left at $tmpdir/$tmpdiff"
fi
