#!/bin/sh

TEMPDIFF='/tmp/diff.pdf'

if [ ! -f $1 ]
then
	echo "!ERROR: file $1 not found. No diff performed"
	exit 0
fi

if [ ! -f $2 ]
then
	echo "!ERROR: file $2 not found. No diff performed"
	exit 0
fi

echo "Diffing $1 vs $2"
/home/jhonny/src/diff-pdf/diff-pdf -msg --output-diff=$TEMPDIFF $1 $2 \
	|| evince $TEMPDIFF
