#!/bin/bash

if [ -z "$tmpdiff" ]; then
    mkdir -p /tmp/diff-pdf
    tmpdiff="/tmp/diff-pdf/diff.pdf"
fi

if [ ! -f $1 ]
then
	echo "!ERROR: file $1 not found. No diff performed"
	exit 0
fi

if [ ! -f $2 ]
then
	echo "!ERROR: file $2 not found. No diff performed"
	exit 0
fi

create_diff() {
    index=$(ls -1 /tmp/diff-pdf/ | wc -l)
    let index++
    newtmpdiff="/tmp/diff-pdf/diff-$index.pdf"
    mv $tmpdiff $newtmpdiff
}

echo "Diffing $1 vs $2"
if [ -z "$noview" ]; then
    diff-pdf -ms --output-diff=$tmpdiff $1 $2 || evince $tmpdiff
else
    diff-pdf -ms --output-diff=$tmpdiff $1 $2 || create_diff
fi
