#!/bin/sh

BASENAME=$(basename $1)

cd LatexClass/dist/tex/latex/lhexsheet

if echo "$1" | grep -q 'packages';
then
    DTX_FILE=packages/$BASENAME
    cd packages
    latex *.ins
    cd ..
else
    DTX_FILE=$BASENAME
    latex *.ins
fi

ldoc $DTX_FILE
