#!/bin/sh

usage() {
	echo "lhdoc <DTX_FILE>"
	echo "Either current directory or its parent"
	echo "must contain a 'package-documentation'"
	echo "directory."
	exit 1
}

DTX_FILE=$1

BASENAME=$(basename $1 .dtx)

export TEXINPUTS=packages//:

texfot --ignore 'Overfull|Underfull' pdflatex -shell-escape -output-directory=package-documentation -halt-on-error "$DTX_FILE" \
&& makeindex -s gind.ist package-documentation/$BASENAME.idx \
&& makeindex -s gglo.ist -o package-documentation/$BASENAME.gls package-documentation/$BASENAME.glo \
&& texfot --ignore 'Overfull|Underfull' pdflatex -shell-escape -output-directory=package-documentation -halt-on-error "$DTX_FILE"
