#!/bin/bash

for arg in "$@"
do
    case "$arg" in
        -d)
            for i in "$@"
            do
                case "$i" in
                    -*)
                        ;;
                    *)
                        dir="$i"
                        ;;
                esac
            done
            ;;
    esac
done

if [ -z "$dir" ]; then
    dir=test
fi

counter=0

tmpdir=/tmp/diff-pdf
rm -rf $tmpdir
mkdir -p $tmpdir

if [ -z "$local" ]; then
    export noview=1
    find $dir -name '*.pdf' | parallel difp '../sharelatex/{} {}'
else
    find $dir -name '*.pdf' | parallel difp '{} {}.old'
fi

if [ ! -z "$(find $tmpdir -name *.pdf)" ]; then
    for pdf in $tmpdir/*.pdf; do
        atril $pdf
    done
else
    echo $tmpdir empty. Deleting.
    rm -rf $tmpdir
    exit 0
fi

echo "Delete $tmpdir?"
echo "	Yes (Y). No (N)."
read action
case "$action" in
    Y|y)
        echo "Deleting $tmpdir"
        rm -rf $tmpdir
        ;;
    N|n)
        echo "Keeping $tmpdir"
        ;;
    *)
        echo "Input $action not recognized"
        exit 1
        ;;
esac
