#!/bin/bash

for arg in "$@"
do
    case "$arg" in
        -d)
            for i in "$@"
            do
                case "$i" in
                    -*)
                        ;;
                    *)
                        dir="$i"
                        ;;
                esac
            done
            ;;
    esac
done

if [ -z "$dir" ]; then
    dir=test
fi

counter=0

rm -rf /tmp/diff-pdf
mkdir -p /tmp/diff-pdf

if [ -z "$local" ]; then
    for i in $(find $dir -name *.pdf); do
        noview=1 difp ../sharelatex/$i $i
    done
else
    for i in $(find $dir -name main.pdf); do
        noview=1 difp $i $i.old
    done
fi
