#!/bin/sh

FILENAME=$1

BASENAME=$(basename $FILENAME .pdf)

gs \
 -sOutputFile=$BASENAME-bw.pdf \
 -sDEVICE=pdfwrite \
 -sColorConversionStrategy=Gray \
 -dProcessColorModel=/DeviceGray \
 -dCompatibilityLevel=1.4 \
 -dNOPAUSE \
 -dBATCH \
 $FILENAME
