#!/bin/sh

relpath=$(readlink -f $1 | ssam 'x/\/home\/jhonny\/git\/sharelatex\//d')

cd /home/jhonny/git/sharelatex

#time texfot ./compile-test.sh $relpath | egrep -v '[Ww]arning|Font|lor page stack 0|Underfull|Overfull'

echo $relpath

./compile-test.sh $relpath
