#!/bin/sh

relpath=$(readlink -f $1 | ssam 'x/\/home\/jhonny\/projects\/linguahouse\//d')
currbranch=$(echo $relpath | cut -d '/' -f 1)

cd /home/jhonny/projects/linguahouse/$currbranch
relpath=$(echo $relpath | ssam 'x/'$currbranch'\//d')

./compile-test.sh $relpath
