#!/usr/bin/lua

local workh = {}

workh.month_days = {31,28,31,30,31,30,31,31,30,31,30,31}
workh.month_days_weekendless = {22,20,23,20,23,22,21,23,21,22,22,21}

function workh.calc_hours (hours)
    current_date = os.date("*t")
    total_hours = 100
    remaining_hours = 100 - hours
    remaining_days = workh.month_days[current_date.month] - current_date.day
    amount_weekends = workh.month_days[current_date.month] - workh.month_days_weekendless[current_date.month]
    remaining_days_weekendless = workh.month_days_weekendless[current_date.month] - (current_date.day - amount_weekends)

    print("Counting weekends:")
    print("  Remaining days: " .. remaining_days)
    print("  Hours per day: " .. remaining_hours/remaining_days)
    -- TODO:
    -- print("Without weekends:")
    -- print("  Remaining days: " .. workh.month_days_weekendless[current_date.month])
    -- print("  Hours per day: " .. remaining_hours/workh.month_days_weekendless[current_date.month])
end

args = {...}
workh.hours = args[1]

workh.calc_hours(workh.hours)