#!/usr/bin/env python3

import subprocess as sp
import re
import sys
import os

winid = path = os.environ["winid"]

# TODO: handle empty stdin
p = sp.run("nuspell", stdout=sp.PIPE, stderr=sp.PIPE)

out = p.stdout.decode("utf-8")

wrong = re.findall(r'Wrong: \w+\.', out)
if wrong == None:
    print("All ok!")
    exit(0)

correct = re.findall(r'(How about: )(.*)', out)

for i,phrase in enumerate(wrong):
    print(phrase)
    word = re.findall(r'\w+', phrase)
    corrections = re.findall(r'\w+', correct[i][1])
    corrections = corrections[0:10]
    for j in corrections:
        print("\taddr"+" "+word[1]+" "+winid+" "+"&&"+" "+"data"+" "+j+" "+winid)